Modified workflow to include deployment to Staging before production

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,11 +24,11 @@ jobs:
       - name: Adding EC2 host to known_hosts
         run: |
           mkdir -p ~/.ssh
-          ssh-keyscan -H 16.171.141.46 >> ~/.ssh/known_hosts
+          ssh-keyscan -H 13.61.0.217 >> ~/.ssh/known_hosts
 
       - name: Prepare server
         run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@16.171.141.46 "
+          ssh -o StrictHostKeyChecking=no ubuntu@13.61.0.217 "
 
             set -e
 
@@ -39,61 +39,59 @@ jobs:
             fi
 
             #Create necessary directories
-            sudo mkdir -p /var/www/releases
+            sudo mkdir -p /var/www/staging/releases
 
             #Set ownership
             sudo chown -R ubuntu:ubuntu /var/www
 
-            #Configure nginx root to /current
-            sudo sed -i 's|root /var/www/html;|root /var/www/html/current;|' /etc/nginx/sites-available/default
+            #Replace nginx default config file with the one in devops-project/nginx
+            sudo mv /devops-project/nginx/default.conf /etc/nginx/sites-available/default
 
             #Restart nginx
             sudo systemctl restart nginx
 
           "
 
-      - name: Deploy to EC2 without downtime
+      - name: Deploy to Staging
         run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@16.171.141.46 "
+          ssh -o StrictHostKeyChecking=no ubuntu@13.61.0.217 "
             set -e  #Exit if any command fails
 
             #Ensure release folder exists
-            mkdir -p /var/www/releases
-
-            #Save previous release (if current exists)
-            if [ -L /var/www/html/current ]; then
-              PREV_RELEASE=\$(readlink /var/www/html/current)
-            else
-              PREV_RELEASE=''
-            fi
+            mkdir -p /var/www/staging/releases
 
             #Create a unique release folder with timestamp
-            NEW_RELEASE=/var/www/releases/release-$(date +%s)
+            NEW_RELEASE=/var/www/staging/releases/release-$(date +%s)
             mkdir -p \$NEW_RELEASE
             echo "Deploying to:" \$NEW_RELEASE
 
             #Upload all files to the new release
             rsync -av --delete ~/devops-project/web/ \$NEW_RELEASE
 
-            #Update symlink so that Nginx serves the new release
-            ln -sfn \$NEW_RELEASE /var/www/html/current
+            #Update symlink so that Nginx serves the new release from the staging folder
+            ln -sfn \$NEW_RELEASE /var/www/staging/current
             echo "Deployment complete"
           "
 
-      - name: Verify deployment
+      - name: Test Staging Deployment
         run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@16.171.141.46 "
-            STATUS=\$(curl -s -o /dev/null -w '%{http_code}' http://16.171.141.46/index.html)
+          ssh -o StrictHostKeyChecking=no ubuntu@13.61.0.217 "
+            STATUS=\$(curl -s -o /dev/null -w '%{http_code}' http://16.171.141.46/staging/index.html)
             if [ \'\$STATUS\' -ne 200 ]; then
-              echo 'Deplyment failed, rolling back...'
-              if [ -n \"\$PREV_RELEASE\" ]; then
-                ln -sfn \$PREV_RELEASE /var/www/html/current
-                echo 'Rollback complete'
-              else
-                echo 'Deployment successful'
-              fi
+              echo 'Staging failed'
+              exit 1
+            else
+              echo 'Staging ok'
             fi
+            
           "
+
+      - name: Deploy to Production
+        if: success()
+        run: |
+          ssh -o StrictHostKeyChecking=no ubuntu@13.61.0.217 "
+            ln -sfn /var/www/staging/current /var/www/html/current
+
 
       - name: Keep at least 3 releases, delete older ones
         run: |
