Added rollback features

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,17 +43,36 @@ jobs:
             #Ensure release folder exists
             mkdir -p /var/www/releases
 
+            #Save previous release (if current exists)
+            if [ -L /var/www/html/current ]; then
+              PREV_RELEASE=\$(readlink /var/www/html/current)
+            else
+              PREV_RELEASE=''
+            fi
+
             #Create a unique release folder with timestamp
-            RELEASE_DIR=/var/www/releases/release-$(date +%s)
-            mkdir -p \$RELEASE_DIR
-            echo "Deploying to:" \$RELEASE_DIR
+            NEW_RELEASE=/var/www/releases/release-$(date +%s)
+            mkdir -p \$NEW_RELEASE
+            echo "Deploying to:" \$NEW_RELEASE
 
             #Upload all files to the new release
-            rsync -av --delete ~/devops-project/web/ \$RELEASE_DIR
+            rsync -av --delete ~/devops-project/web/ \$NEW_RELEASE
 
             #Update symlink so that Nginx serves the new release
             ln -sfn \$RELEASE_DIR /var/www/html/current
             echo "Deployment complete"
+
+            #Verify deployment
+            if [ ! -f /var/www/html/current ]; then
+              echo "Deplyment failed, rolling back..."
+              if [ -n \"\$PREV_RELEASE\" ]; then
+                ln -sfn \$PREV_RELEASE /var/www/html/current
+                echo "Rollback complete"
+              fi
+              exit 1
+            fi
+
+            echo "Deployment successful"
 
             #Keep last 3 releases, delete older ones
             ls -dt /var/www/releases/* | tail -n +4 | xargs rm -rf
